---
- name: install
  package:
    name: cachefilesd
    state: "{{ cachefilesd_package_state }}"

- name: enable
  template:
    src: cachefilesd.j2
    dest: /etc/default/cachefilesd

- name: configure
  template:
    src: cachefilesd_config.j2
    dest: /etc/cachefilesd.conf

- name: start
  service:
    name: cachefilesd
    state: restarted
    enabled: yes
